name: On Push CI/CD
on:
  push:
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Display event name
        run: echo ${{ gitverse.event_name }}
      - name: Display Workflow
        run: echo ${{ gitverse.workflow }}
      - name: Display repository name
        run: echo ${{ gitverse.Repository}}
      - name: Display repository owner
        run: echo ${{ gitverse.repository_owner }}
      - name: Display actor
        run: echo ${{ gitverse.actor }}