version: '3.8'

services:
  app:
    image: ${REGISTRY}/${IMAGE_NAME}:${TAG}
    restart: unless-stopped
    env_file: .env.prod
    ports:
      - "80:80"
    volumes:
      - ./storage:/app/storage
      - ./logs:/var/log/nginx
    networks:
      - nft-network

networks:
  nft-network:
    driver: bridge