name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: nft-church-dev.cr.cloud.ru
  IMAGE_NAME: frontend
  VM_IP: 87.242.118.221
  VM_USER: admin

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.EVO_CR_LOGIN_DEV }}
        password: ${{ secrets.EVO_CR_PWD_DEV }}

    - name: Build and Push
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

  deploy-to-vm:
    runs-on: ubuntu-latest
    needs: build-and-push
    timeout-minutes: 10

    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

    - name: Deploy configuration
      run: |
        # 1. Проверка существования файла локально
        if [ ! -f "docker/prod/docker-compose.prod.yml" ]; then
          echo "::error::docker-compose.prod.yml not found!"
          exit 1
        fi
    
        # 2. Создание временной директории
        mkdir -p ./tmp_deploy
    
        # 3. Копирование с сохранением прав
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
          --rsync-path="sudo rsync" \
          docker/prod/docker-compose.prod.yml \
          ${VM_USER}@${VM_IP}:/opt/nft-church/
    
        # 4. Альтернативный вариант через SSH pipe
        cat docker/prod/docker-compose.prod.yml | \
          ssh -o StrictHostKeyChecking=no ${VM_USER}@${VM_IP} \
          "sudo tee /opt/nft-church/docker-compose.prod.yml >/dev/null"
    
        # 5. Проверка на стороне сервера
        ssh -o StrictHostKeyChecking=no ${VM_USER}@${VM_IP} << 'EOL'
        echo "File contents:"
        sudo ls -la /opt/nft-church/docker-compose.prod.yml
        sudo cat /opt/nft-church/docker-compose.prod.yml | head -n 5
        EOL

    - name: Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ${VM_USER}@${VM_IP} << 'EOL'
        # Pull and run new container
        docker login -u ${{ secrets.EVO_CR_LOGIN_DEV }} -p ${{ secrets.EVO_CR_PWD_DEV }} ${{ env.REGISTRY }}
        docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

        # Graceful update
        docker compose -f /opt/nft-church/docker-compose.prod.yml down
        docker compose -f /opt/nft-church/docker-compose.prod.yml up -d

        # Cleanup
        docker image prune -af
        EOL