name: Secure Container Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: nft-church-dev.cr.cloud.ru
  IMAGE_NAME: lanqvist/nft-church

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
    - name: Checkout with LFS
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true

    - name: Validate critical files
      run: |
        required_files=("package.json" "package-lock.json" "docker/Dockerfile" "docker/nginx/nginx.conf")
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "::error file=$file::Missing required file: $file"
            exit 1
          fi
        done

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        buildkitd-config: |
          [worker.oci]
            gckeepstorage = 30
          [registry."${REGISTRY}"]
            http = true
            insecure = true

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name == 'push' }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        secrets: |
          "NPM_TOKEN=${{ secrets.NPM_TOKEN }}"
      env:
        NODE_ENV: production
        BUILDKIT_PROGRESS: plain

    - name: Scan image for vulnerabilities
      if: always()
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        format: 'sarif'
        output: trivy-results.sarif
        severity: 'HIGH,CRITICAL'