name: React Docker Deploy

on:
  push:
    branches: [main]
  pull_request:
      branches: [ "main" ]

env:
  REGISTRY: nft-church-dev.cr.cloud.ru
  IMAGE_NAME: lanqvist/nft-church

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate files
      run: |
        if [ ! -f package-lock.json ]; then
          echo "::error::package-lock.json not found!"
          exit 1
        fi
        if [ ! -f docker/Dockerfile ]; then
          echo "::error::Dockerfile missing!"
          exit 1
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        buildkitd-config-inline: |
          [registry."${REGISTRY}"]
            http = true
            insecure = true

    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.EVO_CR_LOGIN_DEV }}
        password: ${{ secrets.EVO_CR_PWD_DEV }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max